### ISSUE TITLE
Changing color when CMYK image is converted

### ISSUE THREAD

**Issue by nashiox** [livesense-inc/fanlin#14]
When you convert CMYK images the color changes, but can you fix it?

**Comment by ieee0824** [comment]
I want image samples.

**Comment by nashiox** [comment]
CMYK Raw Image:
![raw](https://user-images.githubusercontent.com/13981050/32639079-741b9c6a-c605-11e7-94f8-4e23be7a99c0.jpg)

Converted Image:
![converted](https://user-images.githubusercontent.com/13981050/32639082-77dcf1b4-c605-11e7-959c-b1db0395cb40.jpg)

Maybe they both look the same in the browser.
It looks the same as Chrome Stable.
Please check with a properly visible browser such as Chrome Canary build.

**Comment by ieee0824** [comment]
I made it for the time being.
https://gist.github.com/ieee0824/8e6d9e0740db3891867ac9a2d4d722e0
https://github.com/ieee0824/libcmyk

**Comment by nashiox** [comment]
👍
